# Generated by Django 5.2.14 on 2026-09-01 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0003_cms_page'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cmspage',
            new_name='governance__is_publ_d9e9b2_idx',
            old_name='governance_cms_ispub_idx',
        ),
        migrations.RenameIndex(
            model_name='cmspage',
            new_name='governance__show_in_a11bcd_idx',
            old_name='governance_cms_footer_idx',
        ),
        migrations.RenameIndex(
            model_name='cmspage',
            new_name='governance__slug_c9da1b_idx',
            old_name='governance_cms_slug_idx',
        ),
    ]
