# Generated by Django 5.2.14 on 2026-06-03 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='technicians', to='tasks.skill'),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='accounts_us_role_1fa9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='accounts_us_is_acti_a5841d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedprofessional',
            unique_together={('user', 'professional')},
        ),
        migrations.AddIndex(
            model_name='technicianprofile',
            index=models.Index(fields=['is_verified'], name='accounts_te_is_veri_7bcf9a_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianprofile',
            index=models.Index(fields=['availability_status'], name='accounts_te_availab_a8f750_idx'),
        ),
    ]
