# Generated by Django 5.2.14 on 2026-06-08 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTPChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('purpose', models.CharField(choices=[('registration', 'Registration'), ('login', 'Login'), ('verification', 'Verification'), ('profile_change', 'Profile Change')], default='verification', max_length=20)),
                ('code_hash', models.CharField(max_length=255)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_phone_otp_challenge',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone'], name='accounts_ph_phone_d8d007_idx'), models.Index(fields=['purpose'], name='accounts_ph_purpose_a1b82e_idx'), models.Index(fields=['expires_at'], name='accounts_ph_expires_7566a0_idx')],
            },
        ),
    ]
