# Generated by Django 5.2.14 on 2026-06-11 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_phoneotpchallenge'),
        ('tasks', '0004_bid_active_bid_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('service_type', models.CharField(choices=[('onsite', 'On-site'), ('remote', 'Remote')], default='onsite', max_length=10)),
                ('coverage_area', models.CharField(blank=True, max_length=255)),
                ('pricing_model', models.CharField(choices=[('fixed', 'Fixed'), ('hourly', 'Hourly'), ('range', 'Range')], default='fixed', max_length=10)),
                ('pricing_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pricing_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_services', to='tasks.category')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_technician_service',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service_type'], name='accounts_te_service_6d71b8_idx'), models.Index(fields=['pricing_model'], name='accounts_te_pricing_3a8fe9_idx'), models.Index(fields=['is_active'], name='accounts_te_is_acti_65b8b3_idx')],
            },
        ),
    ]
