# Generated by Django 5.2.14 on 2026-09-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_technicianservice'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='technicianprofile',
                    name='address',
                    field=models.CharField(blank=True, max_length=255),
                ),
                migrations.AddField(
                    model_name='technicianprofile',
                    name='date_of_birth',
                    field=models.DateField(blank=True, null=True),
                ),
            ],
            database_operations=[]
        )
    ]
