# Generated by Django 5.2.14 on 2026-09-01 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_technicianprofile_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technicianprofile',
            old_name='date_of_birth',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='technicianprofile',
            old_name='address',
            new_name='residential_address',
        ),
    ]
