# Generated by Django 5.2.14 on 2026-09-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_date_of_birth_technicianprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='technicianprofile',
                    name='education_level',
                    field=models.CharField(blank=True, max_length=255),
                ),
                migrations.AddField(
                    model_name='technicianprofile',
                    name='expertise_level',
                    field=models.CharField(blank=True, max_length=100),
                ),
            ],
            database_operations=[]
        )
    ]
