# Generated by Django 5.2.14 on 2026-06-03 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pending_escrow', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet_wallet',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('pending', 'Pending')], max_length=10)),
                ('category', models.CharField(choices=[('earnings', 'Earnings'), ('withdrawal', 'Withdrawal'), ('escrow_hold', 'Escrow Hold'), ('escrow_release', 'Escrow Release'), ('refund', 'Refund')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='tasks.task')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet')),
            ],
            options={
                'db_table': 'wallet_transaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet'], name='wallet_tran_wallet__4da541_idx'), models.Index(fields=['type'], name='wallet_tran_type_fa9e01_idx'), models.Index(fields=['category'], name='wallet_tran_categor_3584b0_idx'), models.Index(fields=['status'], name='wallet_tran_status_a49b73_idx'), models.Index(fields=['-created_at'], name='wallet_tran_created_0b36a1_idx')],
            },
        ),
    ]
