# Generated by Django 5.2.14 on 2026-06-03 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('services_offered', models.JSONField(blank=True, default=list)),
                ('company_size', models.CharField(blank=True, max_length=50)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('cover_url', models.URLField(blank=True, max_length=500)),
                ('about', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('headquarters', models.CharField(blank=True, max_length=255)),
                ('business_hours', models.JSONField(blank=True, default=list)),
                ('is_verified', models.BooleanField(default=False)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('team_size', models.PositiveIntegerField(default=0)),
                ('completed_tasks', models.PositiveIntegerField(default=0)),
                ('response_time', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Company profiles',
                'db_table': 'companies_profile',
            },
        ),
        migrations.CreateModel(
            name='CompanyCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='companies.companyprofile')),
            ],
            options={
                'db_table': 'companies_certification',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CompanyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Start'), ('completed', 'Completed')], default='active', max_length=20)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('timeline', models.CharField(blank=True, max_length=255)),
                ('milestones_total', models.PositiveIntegerField(default=0)),
                ('milestones_completed', models.PositiveIntegerField(default=0)),
                ('payment_status', models.CharField(choices=[('funded', 'Funded in Escrow'), ('awaiting', 'Awaiting Deposit'), ('paid', 'Fully Paid')], default='awaiting', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='companies.companyprofile')),
            ],
            options={
                'db_table': 'companies_project',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('text', models.TextField(blank=True)),
                ('service', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='companies.companyprofile')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'companies_review',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='companies.companyprofile')),
            ],
            options={
                'db_table': 'companies_service',
                'ordering': ['title'],
            },
        ),
    ]
